# Site settings
title: Alistair Taylor
description: Experienced Environment/Release Manager
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alistair-taylor.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alistair Taylor
user_description: I'm a Software Engineer, always searching for the next challenge. Lately I have been immersed in the <b>alternative finance world</b> working for Goji Investments, a London based startup trying to create a platform allowing investors access to a range of alternative investments.
user_title: Experienced Environment/Release Manager
email: alistairtaylor@hotmail.co.uk
github_username:  alistair-taylor
linkedin_username: alistair_taylor

exclude: ['package.json', 'src' , 'node_modules']
